version: "3.9"
services:
  b_agent:
    build:
      context: "./docker/build_agent"
      dockerfile: "Dockerfile"
    working_dir: /app
    volumes:
      - .:/app

  t_agent:
    build:
      context: "./docker/test_agent"
      dockerfile: "Dockerfile"
    working_dir: /app
    volumes:
      - .:/app
